"""empty message

Revision ID: 044af18b3978
Revises: 59158926c2be
Create Date: 2017-10-30 17:16:42.184903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '044af18b3978'
down_revision = '59158926c2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piano', 'name')
    op.drop_column('piano', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('image', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('piano', sa.Column('name', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
