"""empty message

Revision ID: 225bb852bf59
Revises: ce52a0722b79
Create Date: 2017-10-30 17:55:36.988950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '225bb852bf59'
down_revision = 'ce52a0722b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_1', 'image', type_='foreignkey')
    op.drop_column('image', 'piano_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('piano_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_1', 'image', 'piano', ['piano_id'], ['id'])
    # ### end Alembic commands ###
