"""empty message

Revision ID: 57e607eb8332
Revises: 225bb852bf59
Create Date: 2017-10-30 18:51:31.945021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e607eb8332'
down_revision = '225bb852bf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('piano_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'piano', ['piano_id'], ['id'])
    op.drop_column('piano', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('image', mysql.VARCHAR(length=250), nullable=True))
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'piano_id')
    # ### end Alembic commands ###
