"""empty message

Revision ID: 59158926c2be
Revises: 686d42c57a61
Create Date: 2017-10-30 17:14:01.874773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59158926c2be'
down_revision = '686d42c57a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piano', 'image')
    # ### end Alembic commands ###
