"""empty message

Revision ID: 686d42c57a61
Revises: 79deac7fa30d
Create Date: 2017-10-25 15:24:25.247648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '686d42c57a61'
down_revision = '79deac7fa30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piano', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('image', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
