"""empty message

Revision ID: 79ae52754748
Revises: 6309354d807f
Create Date: 2017-10-13 16:03:12.859327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79ae52754748'
down_revision = '6309354d807f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('img', sa.String(length=120), nullable=True))
    op.add_column('piano', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('piano', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('piano', sa.Column('title', sa.String(length=120), nullable=False))
    op.add_column('piano', sa.Column('url', sa.String(length=120), nullable=True))
    op.drop_column('piano', 'name')
    op.drop_column('piano', 'geolong')
    op.drop_column('piano', 'geolat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('geolat', mysql.FLOAT(), nullable=False))
    op.add_column('piano', sa.Column('geolong', mysql.FLOAT(), nullable=False))
    op.add_column('piano', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('piano', 'url')
    op.drop_column('piano', 'title')
    op.drop_column('piano', 'lon')
    op.drop_column('piano', 'lat')
    op.drop_column('piano', 'img')
    # ### end Alembic commands ###
