"""empty message

Revision ID: 79deac7fa30d
Revises: ea3b91297257
Create Date: 2017-10-25 14:55:37.785560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79deac7fa30d'
down_revision = 'ea3b91297257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('piano_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piano_id'], ['piano.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('piano', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('piano', sa.Column('image', sa.String(length=120), nullable=True))
    op.add_column('piano', sa.Column('name', sa.String(length=120), nullable=True))
    op.alter_column('piano', 'bio',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('piano', 'lat',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('piano', 'lon',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('piano', 'img')
    op.drop_column('piano', 'is_active')
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'city')
    op.add_column('piano', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('piano', sa.Column('img', mysql.VARCHAR(length=120), nullable=True))
    op.alter_column('piano', 'lon',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('piano', 'lat',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('piano', 'bio',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('piano', 'name')
    op.drop_column('piano', 'image')
    op.drop_column('piano', 'active')
    op.drop_table('image')
    # ### end Alembic commands ###
