"""empty message

Revision ID: 95b53f8737b8
Revises: 1d84b4c302aa
Create Date: 2017-10-11 16:56:00.780135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b53f8737b8'
down_revision = '1d84b4c302aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=560), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user')
    op.add_column('piano', sa.Column('volunteer_id', sa.Integer(), nullable=True))
    op.drop_constraint('piano_ibfk_1', 'piano', type_='foreignkey')
    op.create_foreign_key(None, 'piano', 'volunteer', ['volunteer_id'], ['id'])
    op.drop_column('piano', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'piano', type_='foreignkey')
    op.create_foreign_key('piano_ibfk_1', 'piano', 'user', ['user_id'], ['id'])
    op.drop_column('piano', 'volunteer_id')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=560), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('volunteer')
    # ### end Alembic commands ###
