"""empty message

Revision ID: ce52a0722b79
Revises: 044af18b3978
Create Date: 2017-10-30 17:35:32.060001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce52a0722b79'
down_revision = '044af18b3978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piano', 'image')
    # ### end Alembic commands ###
