"""empty message

Revision ID: ea3b91297257
Revises: 79ae52754748
Create Date: 2017-10-13 16:07:39.749348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3b91297257'
down_revision = '79ae52754748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piano', sa.Column('bio', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piano', 'bio')
    # ### end Alembic commands ###
